<?php

namespace Mihdan\IndexNow\SEOCore\SitemapSettings;

/**
 * Provides XSL stylesheets to style custom, video, and news sitemaps.
 *
 * Mirrors the WordPress core WP_Sitemaps_Stylesheet design (render_stylesheet(),
 * get_sitemap_stylesheet(), get_stylesheet_css()).
 */
class SitemapStylesheet
{
	const CUSTOM_TYPE = 'custom';
	const VIDEO_TYPE  = 'video';
	const NEWS_TYPE   = 'news';

	public function __construct()
	{
		add_action('init', [$this, 'add_rewrite_rules']);
		add_filter('query_vars', [$this, 'query_vars']);
		add_action('template_redirect', [$this, 'maybe_render'], 1);
	}

	/**
	 * Add rewrite rules for the custom, video, and news sitemap XSL stylesheets.
	 */
	public function add_rewrite_rules(): void
	{
		add_rewrite_rule('^wp-sitemap-custom\.xsl$', 'index.php?sitemap-stylesheet=custom', 'top');
		add_rewrite_rule('^wp-sitemap-crawlwpcustom\.xsl$', 'index.php?sitemap-stylesheet=custom', 'top');

		add_rewrite_rule('^wp-sitemap-video\.xsl$', 'index.php?sitemap-stylesheet=video', 'top');
		add_rewrite_rule('^wp-sitemap-crawlwpvideo\.xsl$', 'index.php?sitemap-stylesheet=video', 'top');

		add_rewrite_rule('^wp-sitemap-news\.xsl$', 'index.php?sitemap-stylesheet=news', 'top');
		add_rewrite_rule('^wp-sitemap-crawlwpnews\.xsl$', 'index.php?sitemap-stylesheet=news', 'top');
	}

	/**
	 * Ensure sitemap-stylesheet query var is registered.
	 *
	 * @param string[] $vars
	 * @return string[]
	 */
	public function query_vars(array $vars): array
	{
		if (!in_array('sitemap-stylesheet', $vars, true)) {
			$vars[] = 'sitemap-stylesheet';
		}

		return $vars;
	}

	/**
	 * Normalize custom, video, or news stylesheet type string.
	 */
	public static function normalize_type(string $type): ?string
	{
		return match ($type) {
			'custom', 'crawlwpcustom' => self::CUSTOM_TYPE,
			'video', 'crawlwpvideo'   => self::VIDEO_TYPE,
			'news', 'crawlwpnews'     => self::NEWS_TYPE,
			default                   => null,
		};
	}

	/**
	 * Render the stylesheet if requested on template_redirect.
	 */
	public function maybe_render(): void
	{
		$type = sanitize_text_field((string) get_query_var('sitemap-stylesheet'));
		if ($type === '') {
			return;
		}

		$normalized = self::normalize_type($type);
		if ($normalized === null) {
			return;
		}

		if ($normalized === self::VIDEO_TYPE && SitemapSettings::get('video_enabled', 'off') !== 'on') {
			if (function_exists('wp_die')) {
				wp_die(
					esc_html__('The Video Sitemap is disabled. Enable it under Settings → Advanced → Sitemap.', 'mihdan-index-now'),
					esc_html__('Video Sitemap disabled', 'mihdan-index-now'),
					['response' => 404]
				);
			}
			return;
		}

		if ($normalized === self::NEWS_TYPE && SitemapSettings::get('news_enabled', 'off') !== 'on') {
			if (function_exists('wp_die')) {
				wp_die(
					esc_html__('The News Sitemap is disabled. Enable it under Settings → Advanced → Sitemap.', 'mihdan-index-now'),
					esc_html__('News Sitemap disabled', 'mihdan-index-now'),
					['response' => 404]
				);
			}
			return;
		}

		$this->render_stylesheet($normalized);
	}

	/**
	 * Renders the XSL stylesheet depending on the sitemap type.
	 *
	 * @param string $type Stylesheet type. 'custom', 'video', or 'news'.
	 * @return never
	 */
	public function render_stylesheet(string $type)
	{
		if (!headers_sent()) {
			header('Content-Type: application/xml; charset=UTF-8');
		}

		echo $this->get_sitemap_stylesheet($type);

		exit;
	}

	/**
	 * Returns the escaped XSL for the given sitemap type.
	 *
	 * @param string $type Stylesheet type. Either 'custom', 'video', or 'news'.
	 * @return string
	 */
	public function get_sitemap_stylesheet(string $type = self::CUSTOM_TYPE): string
	{
		$normalized = self::normalize_type($type) ?? self::CUSTOM_TYPE;

		return match ($normalized) {
			self::VIDEO_TYPE => $this->get_video_sitemap_stylesheet(),
			self::NEWS_TYPE  => $this->get_news_sitemap_stylesheet(),
			default          => $this->get_custom_sitemap_stylesheet(),
		};
	}

	/**
	 * Returns the escaped XSL for custom URLs sitemaps.
	 *
	 * @return string
	 */
	public function get_custom_sitemap_stylesheet(): string
	{
		$css         = $this->get_stylesheet_css();
		$title       = esc_xml(__('Custom URLs XML Sitemap', 'mihdan-index-now'));
		$description = sprintf(
			/* translators: %s: CrawlWP link */
			esc_xml(__('This XML Sitemap is generated by %s to make your content more visible for search engines.', 'mihdan-index-now')),
			'CrawlWP'
		);
		$description = str_replace('CrawlWP', '<a target="_blank" href="https://crawlwp.com/">CrawlWP SEO plugin</a>', $description);

		$learn_more  = sprintf(
			'<a href="%s">%s</a>',
			esc_url(__('https://www.sitemaps.org/')),
			esc_xml(__('Learn more about XML sitemaps.'))
		);

		$text = sprintf(
			/* translators: %s: Number of URLs. */
			esc_xml(__('Number of URLs in this XML Sitemap: %s.', 'mihdan-index-now')),
			'<xsl:value-of select="count( sitemap:urlset/sitemap:url )" />'
		);

		$lang    = function_exists('get_language_attributes') ? get_language_attributes('html') : 'lang="en-US"';
		$url     = esc_xml(__('URL'));
		$lastmod = esc_xml(__('Last Modified'));

		$xsl_content = <<<XSL
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
		version="1.0"
		xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
		exclude-result-prefixes="sitemap"
		>

	<xsl:output method="html" encoding="UTF-8" indent="yes" />

	<!--
	  Set variables for whether lastmod occurs for any url in the sitemap.
	  We do this up front because it can be expensive in a large sitemap.
	  -->
	<xsl:variable name="has-lastmod" select="count( /sitemap:urlset/sitemap:url/sitemap:lastmod )" />

	<xsl:template match="/">
		<html {$lang}>
			<head>
				<title>{$title}</title>
				<style>
					{$css}
				</style>
			</head>
			<body>
				<div id="sitemap">
					<div id="sitemap__header">
						<h1>{$title}</h1>
						<p>{$description}</p>
						<p>{$learn_more}</p>
					</div>
					<div id="sitemap__content">
						<p class="text">{$text}</p>
						<table id="sitemap__table">
							<thead>
								<tr>
									<th class="loc">{$url}</th>
									<xsl:if test="\$has-lastmod">
										<th class="lastmod">{$lastmod}</th>
									</xsl:if>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:urlset/sitemap:url">
									<tr>
										<td class="loc"><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc" /></a></td>
										<xsl:if test="\$has-lastmod">
											<td class="lastmod"><xsl:value-of select="sitemap:lastmod" /></td>
										</xsl:if>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</div>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>

XSL;

		$xsl_content = apply_filters('crawlwp_sitemaps_custom_stylesheet_content', $xsl_content);

		return (string) apply_filters('wp_sitemaps_stylesheet_content', $xsl_content);
	}

	/**
	 * Returns the escaped XSL for video sitemaps.
	 *
	 * @return string
	 */
	public function get_video_sitemap_stylesheet(): string
	{
		$css         = $this->get_stylesheet_css();
		$title       = esc_xml(__('Video XML Sitemap', 'mihdan-index-now'));
		$description = sprintf(
			/* translators: %s: CrawlWP link */
			esc_xml(__('This XML Sitemap is generated by WordPress, and improved by %s to make your video content more visible for search engines.', 'mihdan-index-now')),
			'CrawlWP'
		);
		$description = str_replace('CrawlWP', '<a target="_blank" href="https://crawlwp.com">CrawlWP SEO plugin</a>', $description);

		$learn_more  = sprintf(
			'<a href="%s">%s</a>',
			esc_url(__('https://developers.google.com/search/docs/crawling-indexing/sitemaps/video-sitemaps')),
			esc_xml(__('Learn more about video sitemaps.', 'mihdan-index-now'))
		);

		$text = sprintf(
			/* translators: %s: Number of URLs. */
			esc_xml(__('Number of videos in this XML Sitemap: %s.', 'mihdan-index-now')),
			'<xsl:value-of select="count( sitemap:urlset/sitemap:url )" />'
		);

		$lang        = function_exists('get_language_attributes') ? get_language_attributes('html') : 'lang="en-US"';
		$video_col   = esc_xml(__('Video', 'mihdan-index-now'));
		$title_col   = esc_xml(__('Title', 'mihdan-index-now'));
		$url_col     = esc_xml(__('URL'));
		$desc_col    = esc_xml(__('Description', 'mihdan-index-now'));

		$xsl_content = <<<XSL
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
		version="1.0"
		xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
		xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"
		exclude-result-prefixes="sitemap video"
		>

	<xsl:output method="html" encoding="UTF-8" indent="yes" />

	<xsl:variable name="has-thumbnail"   select="count( /sitemap:urlset/sitemap:url/video:video/video:thumbnail_loc )" />
	<xsl:variable name="has-description" select="count( /sitemap:urlset/sitemap:url/video:video/video:description )" />

	<xsl:template match="/">
		<html {$lang}>
			<head>
				<title>{$title}</title>
				<style>
					{$css}
				</style>
			</head>
			<body>
				<div id="sitemap">
					<div id="sitemap__header">
						<h1>{$title}</h1>
						<p>{$description}</p>
						<p>{$learn_more}</p>
					</div>
					<div id="sitemap__content">
						<p class="text">{$text}</p>
						<table id="sitemap__table">
							<thead>
								<tr>
									<xsl:if test="\$has-thumbnail">
										<th class="thumbnail">{$video_col}</th>
									</xsl:if>
									<th class="video-title">{$title_col}</th>
									<th class="loc">{$url_col}</th>
									<xsl:if test="\$has-description">
										<th class="video-desc">{$desc_col}</th>
									</xsl:if>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:urlset/sitemap:url">
									<tr>
										<xsl:if test="\$has-thumbnail">
											<td class="thumbnail">
												<xsl:if test="video:video/video:thumbnail_loc">
													<img src="{video:video/video:thumbnail_loc}" alt="" width="120" style="max-width:120px;height:auto;border-radius:4px;display:block;" />
												</xsl:if>
											</td>
										</xsl:if>
										<td class="video-title">
											<strong><xsl:value-of select="video:video/video:title" /></strong>
										</td>
										<td class="loc">
											<a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc" /></a>
										</td>
										<xsl:if test="\$has-description">
											<td class="video-desc">
												<xsl:value-of select="video:video/video:description" />
											</td>
										</xsl:if>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</div>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>

XSL;

		$xsl_content = apply_filters('crawlwp_sitemaps_video_stylesheet_content', $xsl_content);

		return (string) apply_filters('wp_sitemaps_stylesheet_content', $xsl_content);
	}

	/**
	 * Returns the escaped XSL for Google News sitemaps.
	 *
	 * @return string
	 */
	public function get_news_sitemap_stylesheet(): string
	{
		$css         = $this->get_stylesheet_css();
		$title       = esc_xml(__('Google News XML Sitemap', 'mihdan-index-now'));
		$description = sprintf(
			/* translators: %s: CrawlWP link */
			esc_xml(__('This XML Sitemap is generated by %s for Google News indexing.', 'mihdan-index-now')),
			'CrawlWP'
		);
		$description = str_replace('CrawlWP', '<a target="_blank" href="https://crawlwp.com/">CrawlWP SEO plugin</a>', $description);

		$learn_more  = sprintf(
			'<a href="%s">%s</a>',
			esc_url(__('https://developers.google.com/search/docs/crawling-indexing/sitemaps/news-sitemap')),
			esc_xml(__('Learn more about Google News sitemaps.', 'mihdan-index-now'))
		);

		$text = sprintf(
			/* translators: %s: Number of URLs. */
			esc_xml(__('Number of articles in this XML Sitemap: %s.', 'mihdan-index-now')),
			'<xsl:value-of select="count( sitemap:urlset/sitemap:url )" />'
		);

		$lang            = function_exists('get_language_attributes') ? get_language_attributes('html') : 'lang="en-US"';
		$title_col       = esc_xml(__('Article Title', 'mihdan-index-now'));
		$url_col         = esc_xml(__('URL'));
		$publication_col = esc_xml(__('Publication', 'mihdan-index-now'));
		$date_col        = esc_xml(__('Publication Date', 'mihdan-index-now'));

		$xsl_content = <<<XSL
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
		version="1.0"
		xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
		xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
		exclude-result-prefixes="sitemap news"
		>

	<xsl:output method="html" encoding="UTF-8" indent="yes" />

	<xsl:variable name="has-publication" select="count( /sitemap:urlset/sitemap:url/news:news/news:publication/news:name )" />
	<xsl:variable name="has-pubdate"     select="count( /sitemap:urlset/sitemap:url/news:news/news:publication_date )" />

	<xsl:template match="/">
		<html {$lang}>
			<head>
				<title>{$title}</title>
				<style>
					{$css}
				</style>
			</head>
			<body>
				<div id="sitemap">
					<div id="sitemap__header">
						<h1>{$title}</h1>
						<p>{$description}</p>
						<p>{$learn_more}</p>
					</div>
					<div id="sitemap__content">
						<p class="text">{$text}</p>
						<table id="sitemap__table">
							<thead>
								<tr>
									<th class="news-title">{$title_col}</th>
									<th class="loc">{$url_col}</th>
									<xsl:if test="\$has-publication">
										<th class="publication">{$publication_col}</th>
									</xsl:if>
									<xsl:if test="\$has-pubdate">
										<th class="pubdate">{$date_col}</th>
									</xsl:if>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:urlset/sitemap:url">
									<tr>
										<td class="news-title">
											<strong><xsl:value-of select="news:news/news:title" /></strong>
										</td>
										<td class="loc">
											<a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc" /></a>
										</td>
										<xsl:if test="\$has-publication">
											<td class="publication">
												<xsl:value-of select="news:news/news:publication/news:name" />
												<xsl:if test="news:news/news:publication/news:language">
													(<xsl:value-of select="news:news/news:publication/news:language" />)
												</xsl:if>
											</td>
										</xsl:if>
										<xsl:if test="\$has-pubdate">
											<td class="pubdate">
												<xsl:value-of select="news:news/news:publication_date" />
											</td>
										</xsl:if>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</div>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>

XSL;

		$xsl_content = apply_filters('crawlwp_sitemaps_news_stylesheet_content', $xsl_content);

		return (string) apply_filters('wp_sitemaps_stylesheet_content', $xsl_content);
	}

	/**
	 * Get the stylesheet URL for a given sitemap type.
	 *
	 * @param string $type Stylesheet type: 'custom', 'video', or 'news'.
	 * @return string
	 */
	public static function get_stylesheet_url(string $type = self::CUSTOM_TYPE): string
	{
		global $wp_rewrite;

		$normalized = self::normalize_type($type) ?? self::CUSTOM_TYPE;

		$using_permalinks = isset($wp_rewrite) && is_object($wp_rewrite) && method_exists($wp_rewrite, 'using_permalinks') && $wp_rewrite->using_permalinks();

		if ($using_permalinks) {
			$url = home_url("/wp-sitemap-{$normalized}.xsl");
		} else {
			$url = home_url("/?sitemap-stylesheet={$normalized}");
		}

		$url = apply_filters("crawlwp_sitemap_{$normalized}_stylesheet_url", $url);

		return (string) apply_filters('crawlwp_sitemap_stylesheet_url', $url, $normalized);
	}

	/**
	 * Instance wrapper for get_stylesheet_url.
	 *
	 * @param string $type Stylesheet type: 'custom', 'video', or 'news'.
	 * @return string
	 */
	public function get_sitemap_stylesheet_url(string $type = self::CUSTOM_TYPE): string
	{
		return self::get_stylesheet_url($type);
	}

	/**
	 * Gets the CSS to be included in sitemap XSL stylesheets.
	 *
	 * @return string
	 */
	public function get_stylesheet_css(): string
	{
		$css = '';
		if (class_exists('\WP_Sitemaps_Stylesheet')) {
			$stylesheet = new \WP_Sitemaps_Stylesheet();
			$css = $stylesheet->get_stylesheet_css();
		} else {
			$text_align = function_exists('is_rtl') && is_rtl() ? 'right' : 'left';
			$css = <<<EOF

					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						color: #444;
					}

					#sitemap {
						max-width: 980px;
						margin: 0 auto;
					}

					#sitemap__table {
						width: 100%;
						border: solid 1px #ccc;
						border-collapse: collapse;
					}

			 		#sitemap__table tr td.loc {
						direction: ltr;
					}

					#sitemap__table tr th {
						text-align: {$text_align};
					}

					#sitemap__table tr td,
					#sitemap__table tr th {
						padding: 10px;
					}

					#sitemap__table tr:nth-child(odd) td {
						background-color: #eee;
					}

					a:hover {
						text-decoration: none;
					}

EOF;
		}

		$extra = '
					#sitemap__table td.thumbnail {
						width: 130px;
						text-align: center;
					}
					#sitemap__table td.video-title,
					#sitemap__table td.news-title {
						font-weight: 500;
					}
					#sitemap__table td.video-desc {
						color: #646970;
						font-size: 13px;
					}
					#sitemap__table td.pubdate,
					#sitemap__table td.publication {
						color: #646970;
						font-size: 13px;
						white-space: nowrap;
					}
		';

		return apply_filters('crawlwp_sitemaps_stylesheet_css', $css . $extra);
	}
}
