<?php

namespace Mihdan\IndexNow\SEOCore;

use Mihdan\IndexNow\SEOCore\TitleMeta\Entities;
use Mihdan\IndexNow\SEOCore\TitleMeta\FrontendOutput;

/**
 * Keeps the WordPress core sitemap in sync with the "Hide from search results" toggles
 * and adds hreflang alternate-link support for Polylang, WPML, and TranslatePress.
 */
class Sitemap
{
	public function __construct()
	{
		add_filter('wp_sitemaps_post_types', [$this, 'filter_post_types']);
		add_filter('wp_sitemaps_taxonomies', [$this, 'filter_taxonomies']);
		add_filter('wp_sitemaps_add_provider', [$this, 'filter_providers'], 10, 2);

		add_filter('wp_sitemaps_stylesheet_content', [$this, 'brand_stylesheet']);
		add_filter('wp_sitemaps_stylesheet_index_content', [$this, 'brand_stylesheet']);

		/* Boot whichever multilingual integration is active. */
		$this->setup_multilingual();
	}

	// -------------------------------------------------------------------------
	// Noindex filters (unchanged from original)
	// -------------------------------------------------------------------------

	/**
	 * Drop post types that are hidden from search results.
	 *
	 * @param array $post_types Post type objects keyed by name.
	 *
	 * @return array
	 */
	public function filter_post_types($post_types)
	{
		if (! is_array($post_types)) {
			return $post_types;
		}

		foreach (array_keys($post_types) as $name) {
			if (FrontendOutput::is_noindexed(Entities::post_type_key((string) $name))) {
				unset($post_types[$name]);
			}
		}

		return $post_types;
	}

	/**
	 * Drop taxonomies that are hidden from search results.
	 *
	 * @param array $taxonomies Taxonomy objects keyed by name.
	 *
	 * @return array
	 */
	public function filter_taxonomies($taxonomies)
	{
		if (! is_array($taxonomies)) {
			return $taxonomies;
		}

		foreach (array_keys($taxonomies) as $name) {
			if (FrontendOutput::is_noindexed(Entities::taxonomy_key((string) $name))) {
				unset($taxonomies[$name]);
			}
		}

		return $taxonomies;
	}

	/**
	 * Drop the users provider when author archives are hidden.
	 *
	 * @param mixed  $provider The sitemap provider.
	 * @param string $name     Provider name.
	 *
	 * @return mixed
	 */
	public function filter_providers($provider, $name)
	{
		if ($name === 'users' && FrontendOutput::is_noindexed('author')) {
			return false;
		}

		return $provider;
	}

	// -------------------------------------------------------------------------
	// Stylesheet branding
	// -------------------------------------------------------------------------

	/**
	 * Replace the generic WordPress description in the sitemap XSL stylesheet
	 * with branded text that credits CrawlWP.
	 *
	 * Hooks: wp_sitemaps_stylesheet_content, wp_sitemaps_stylesheet_index_content
	 *
	 * @param string $content Full XSL stylesheet content.
	 * @return string
	 */
	public function brand_stylesheet(string $content): string
	{
		/*
		 * The original description text appears as-is in the XSL (no XML-special
		 * characters), so no escaping is needed for the search string.
		 *
		 * The replacement string contains a literal <a> element, which is valid
		 * XML inside the XSL template that produces HTML output. Do NOT call
		 * esc_xml() on it — that would turn <a href="…"> into &lt;a href=&quot;…&gt;
		 * which browsers would display as literal text instead of a hyperlink.
		 *
		 * Note: on non-English WordPress installations the string is already
		 * translated in the XSL, so str_replace() will find no match and the
		 * function returns $content unchanged (graceful no-op).
		 */
		$original = 'This XML Sitemap is generated by WordPress to make your content more visible for search engines.';
		$branded  = 'This XML Sitemap is generated by WordPress, and improved by <a target="_blank" href="https://crawlwp.com">CrawlWP</a> to make your content more visible for search engines.';

		return str_replace($original, $branded, $content);
	}

	// -------------------------------------------------------------------------
	// Multilingual integration bootstrap
	// -------------------------------------------------------------------------

	/**
	 * Detect active multilingual plugin and boot the appropriate integration.
	 */
	private function setup_multilingual()
	{
		if (defined('POLYLANG_VERSION')) {
			(new Sitemap\Polylang())->setup();
		} elseif (defined('ICL_SITEPRESS_VERSION')) {
			(new Sitemap\WPML())->setup();
		} elseif (defined('TRP_PLUGIN_VERSION')) {
			(new Sitemap\TranslatePress())->setup();
		}
	}
}
