<?php

namespace Mihdan\IndexNow\SEOCore;

use Mihdan\IndexNow\SEOCore\TitleMeta\Entities;
use Mihdan\IndexNow\SEOCore\TitleMeta\FrontendOutput;

/**
 * Keeps the WordPress core sitemap in sync with the "Hide from search results" toggles
 * and adds hreflang alternate-link support for Polylang, WPML, and TranslatePress.
 */
class Sitemap
{
	public function __construct()
	{
		add_filter('wp_sitemaps_post_types', [$this, 'filter_post_types']);
		add_filter('wp_sitemaps_taxonomies', [$this, 'filter_taxonomies']);
		add_filter('wp_sitemaps_add_provider', [$this, 'filter_providers'], 10, 2);

		/* Brand the sitemap stylesheet description (works for any site language). */
		add_filter('wp_sitemaps_stylesheet_content', [$this, 'brand_stylesheet']);
		add_filter('wp_sitemaps_stylesheet_index_content', [$this, 'brand_stylesheet']);

		/* Inject additional CSS into the sitemap stylesheet. */
		add_filter('wp_sitemaps_stylesheet_css', [$this, 'enhance_stylesheet_css']);

		/* Boot whichever multilingual integration is active. */
		$this->setup_multilingual();
	}

	// -------------------------------------------------------------------------
	// Noindex filters (unchanged from original)
	// -------------------------------------------------------------------------

	/**
	 * Drop post types that are hidden from search results.
	 *
	 * @param array $post_types Post type objects keyed by name.
	 *
	 * @return array
	 */
	public function filter_post_types($post_types)
	{
		if (! is_array($post_types)) {
			return $post_types;
		}

		foreach (array_keys($post_types) as $name) {
			if (FrontendOutput::is_noindexed(Entities::post_type_key((string) $name))) {
				unset($post_types[$name]);
			}
		}

		return $post_types;
	}

	/**
	 * Drop taxonomies that are hidden from search results.
	 *
	 * @param array $taxonomies Taxonomy objects keyed by name.
	 *
	 * @return array
	 */
	public function filter_taxonomies($taxonomies)
	{
		if (! is_array($taxonomies)) {
			return $taxonomies;
		}

		foreach (array_keys($taxonomies) as $name) {
			if (FrontendOutput::is_noindexed(Entities::taxonomy_key((string) $name))) {
				unset($taxonomies[$name]);
			}
		}

		return $taxonomies;
	}

	/**
	 * Drop the users provider when author archives are hidden.
	 *
	 * @param mixed  $provider The sitemap provider.
	 * @param string $name     Provider name.
	 *
	 * @return mixed
	 */
	public function filter_providers($provider, $name)
	{
		if ($name === 'users' && FrontendOutput::is_noindexed('author')) {
			return false;
		}

		return $provider;
	}

	// -------------------------------------------------------------------------
	// Stylesheet branding
	// -------------------------------------------------------------------------

	/**
	 * Replace the generic WordPress description in the sitemap XSL stylesheet
	 * with branded text that credits CrawlWP.
	 *
	 * Works for any language: WordPress inserts the description via esc_xml(__())
	 * so we search for the same escaped translated string — it always matches
	 * whatever language the site runs in.
	 *
	 * Hooks: wp_sitemaps_stylesheet_content, wp_sitemaps_stylesheet_index_content
	 *
	 * @param string $content Full XSL stylesheet content.
	 * @return string
	 */
	public function brand_stylesheet(string $content): string
	{
		/*
		 * WordPress builds the XSL with:
		 *   esc_xml( __( 'This XML Sitemap is generated…' ) )
		 * so on a French/German/etc. site the XSL already contains the translated
		 * (and XML-escaped) version of that string. We call esc_xml(__()) here for
		 * the same reason — it resolves to whatever is actually in the XSL.
		 *
		 * The replacement must NOT be esc_xml()-encoded because it contains a
		 * literal <a> element that should render as a real hyperlink in the browser.
		 */
		$original = esc_xml( __( 'This XML Sitemap is generated by WordPress to make your content more visible for search engines.' ) );
		$branded  = 'This XML Sitemap is generated by WordPress, and improved by <a target="_blank" href="https://crawlwp.com">CrawlWP</a> to make your content more visible for search engines.';

		return str_replace($original, $branded, $content);
	}

	/**
	 * Inject minimal additional CSS into the sitemap stylesheet.
	 *
	 * Hook: wp_sitemaps_stylesheet_css
	 *
	 * @param string $css Existing sitemap CSS.
	 * @return string
	 */
	public function enhance_stylesheet_css(string $css): string
	{
		$extra = '

					/* CrawlWP enhancements */
					body {
						background: #f0f0f1;
						margin: 0;
						padding: 0;
					}

					#sitemap {
						background: #fff;
						border-radius: 4px;
						box-shadow: 0 1px 4px rgba(0,0,0,.08);
						margin: 32px auto;
						overflow: hidden;
					}

					#sitemap__header {
						background: #1d2327;
						color: #f0f0f1;
						padding: 24px 32px;
					}

					#sitemap__header h1 {
						color: #fff;
						font-size: 20px;
						margin: 0 0 8px;
					}

					#sitemap__header p {
						color: rgba(255,255,255,.75);
						font-size: 13px;
						margin: 4px 0 0;
					}

					#sitemap__header a {
						color: #72aee6;
					}

					#sitemap__content {
						padding: 24px 32px;
					}

					#sitemap__content .text {
						color: #646970;
						font-size: 13px;
						margin-bottom: 16px;
					}

					#sitemap__table {
						border: 1px solid #dcdcde;
						border-radius: 3px;
						overflow: hidden;
					}

					#sitemap__table tr th {
						background: #f6f7f7;
						border-bottom: 1px solid #dcdcde;
						color: #1d2327;
						font-size: 12px;
						font-weight: 600;
						letter-spacing: .03em;
						text-transform: uppercase;
					}

					#sitemap__table tr:nth-child(odd) td {
						background-color: #fff;
					}

					#sitemap__table tr:nth-child(even) td {
						background-color: #f6f7f7;
					}

					#sitemap__table tr:hover td {
						background-color: #f0f6fc;
					}

					#sitemap__table td.loc a {
						color: #2271b1;
						text-decoration: none;
					}

					#sitemap__table td.loc a:hover {
						text-decoration: underline;
					}

					#sitemap__table td.lastmod,
					#sitemap__table td.changefreq,
					#sitemap__table td.priority {
						color: #646970;
						font-size: 13px;
					}';

		return $css . $extra;
	}

	// -------------------------------------------------------------------------
	// Multilingual integration bootstrap
	// -------------------------------------------------------------------------

	/**
	 * Detect active multilingual plugin and boot the appropriate integration.
	 */
	private function setup_multilingual()
	{
		if (defined('POLYLANG_VERSION')) {
			(new Sitemap\Polylang())->setup();
		} elseif (defined('ICL_SITEPRESS_VERSION')) {
			(new Sitemap\WPML())->setup();
		} elseif (defined('TRP_PLUGIN_VERSION')) {
			(new Sitemap\TranslatePress())->setup();
		}
	}
}
