name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: On push tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install composer requirements
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest
      - name: Prefix dependencies
        run: composer prefix-dependencies
      - name: WordPress plugin deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: mihdan-index-now
